import { defineArrayMember, defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "media", title: "Media" },
    { name: "commerce", title: "Commerce linkage" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "commerceProductId",
      title: "Commerce product ID",
      type: "string",
      group: "commerce",
      description:
        "Stable identifier from the Medusa product, used to link editorial content to the transactional catalog.",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Full description",
      type: "array",
      group: "content",
      of: [{ type: "block" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "collections",
      title: "Collections",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "collection" }],
        }),
      ],
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "category" }],
        }),
      ],
    }),
    defineField({
      name: "material",
      title: "Material / fabric",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "careInformation",
      title: "Care information",
      type: "text",
      rows: 3,
      group: "content",
    }),
    defineField({
      name: "includedItems",
      title: "Included items",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "stylingDetails",
      title: "Styling details",
      type: "array",
      group: "content",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "featured",
      title: "Featured product",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "newArrival",
      title: "New arrival editorial flag",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "editorialLabels",
      title: "Editorial labels",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      group: "media",
      of: [{ type: "productMedia" }],
    }),
    defineField({
      name: "videoUrl",
      title: "Video URL",
      type: "url",
      group: "media",
      validation: (rule) => rule.uri({ allowRelative: false }),
    }),
    defineField({
      name: "socialProof",
      title: "Social proof",
      type: "socialProof",
      group: "content",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "commerceProductId",
      media: "images.0.image",
    },
  },
});
